export interface BankOption {
  code: string;
  name: string;
}

export const FALLBACK_NIGERIAN_BANKS: BankOption[] = [
  { code: '044', name: 'Access Bank' },
  { code: '063', name: 'Access Bank (Diamond)' },
  { code: '035A', name: 'ALAT by WEMA' },
  { code: '000304', name: 'Alternative Bank' },
  { code: '50572', name: 'Bankly MFB' },
  { code: '565', name: 'Carbon' },
  { code: '023', name: 'Citibank Nigeria' },
  { code: '050', name: 'Ecobank Nigeria' },
  { code: '50126', name: 'Eyowo' },
  { code: '51318', name: 'FairMoney Microfinance Bank' },
  { code: '214', name: 'First City Monument Bank (FCMB)' },
  { code: '011', name: 'First Bank of Nigeria' },
  { code: '070', name: 'Fidelity Bank' },
  { code: '00103', name: 'Globus Bank' },
  { code: '058', name: 'GTBank (Guaranty Trust Bank)' },
  { code: '030', name: 'Heritage Bank' },
  { code: '301', name: 'Jaiz Bank' },
  { code: '082', name: 'Keystone Bank' },
  { code: '50211', name: 'Kuda Bank' },
  { code: '50515', name: 'Moniepoint MFB' },
  { code: '120002', name: 'MoMo PSB (MTN)' },
  { code: '999992', name: 'OPay Digital Services (PayCom)' },
  { code: '999991', name: 'PalmPay' },
  { code: '526', name: 'Parallex Bank' },
  { code: '101', name: 'Providus Bank' },
  { code: '125', name: 'Rubies MFB' },
  { code: '51310', name: 'Sparkle Microfinance Bank' },
  { code: '221', name: 'Stanbic IBTC Bank' },
  { code: '068', name: 'Standard Chartered Bank' },
  { code: '232', name: 'Sterling Bank' },
  { code: '100', name: 'SunTrust Bank' },
  { code: '302', name: 'TAJ Bank' },
  { code: '102', name: 'Titan Trust Bank' },
  { code: '032', name: 'Union Bank of Nigeria' },
  { code: '033', name: 'United Bank for Africa (UBA)' },
  { code: '215', name: 'Unity Bank' },
  { code: '566', name: 'VFD Microfinance Bank' },
  { code: '035', name: 'Wema Bank' },
  { code: '057', name: 'Zenith Bank PLC' },
].sort((a, b) => a.name.localeCompare(b.name));
